name: Test & Lint

on:
  push:
    branches: ["main", "dev"]
  pull_request:

jobs:
  test:
    name: 🧪 Lint & Test on Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python (v${{ matrix.python-version }})
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ".[dev]" pytest

      - name: Ruff Lint
        run: ruff check .

      - name: Ruff Format
        run: ruff format --check .

      - name: MyPy Type Check
        run: mypy raito

      - name: Run Tests
        run: pytest
