name: Test & Lint

on:
  push:
    branches: ["main", "dev"]
  pull_request:

jobs:
  test:
    name: 🧪 Lint & Test on Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python (v${{ matrix.python-version }})
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: astral-sh/setup-uv
        uses: astral-sh/setup-uv@v6.3.1

      - name: Sync dependencies
        run: uv sync --all-extras

      - name: Ruff Lint
        run: uv run ruff check .

      - name: Ruff Format
        run: uv run ruff format --check .

      - name: MyPy Type Check
        run: uv run mypy raito

      - name: Run Tests
        run: uv run pytest
