name: Test Release

on:
  push:
    tags:
      - "v*dev*"
      - "v*b*"
      - "v*rc*"

jobs:
  deploy:
    name: 📦 Deploy to TestPyPI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: python -m pip install --upgrade build twine

      - name: Build package
        run: python -m build

      - name: Publish to TestPyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TEST_PYPI_TOKEN }}
        run: twine upload --repository-url https://test.pypi.org/legacy/ dist/*
